import { TEventWithRelations } from "@/entities"
import { DEFAULT_FILTERS } from "@/lib/filter"

// Sample data for the events
export const events: TEventWithRelations[] = [
  {
    id: 1,
    name: "ETHDenver",
    location: "Denver, USA",
    region: "North America",
    country: "USA",
    categories: ["Hackathon", "Conference"],
    domains: ["Ethereum", "Web3"],
    venueType: "in_person",
    startDateTime: new Date("2025-02-23T09:00:00-07:00"),
    endDateTime: new Date("2025-03-03T18:00:00-07:00"),
    links: ["https://ethdenver.com"],
    socials: ["https://twitter.com/ETHDenver"],
    communities: ["https://t.me/ethdenver"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 5, tempmin: -5, temp: 0, humidity: 60 },
  },
  {
    id: 2,
    name: "ETHPrague",
    location: "Prague, Czech Republic",
    region: "Europe",
    country: "Czech Republic",
    categories: ["Hackathon"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-05-31T10:00:00+02:00"),
    endDateTime: new Date("2025-06-02T18:00:00+02:00"),
    links: ["https://ethprague.com"],
    socials: ["https://twitter.com/ETHPrague"],
    communities: ["https://t.me/ethprague"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 22, tempmin: 12, temp: 17, humidity: 55 },
  },
  {
    id: 3,
    name: "ETHBarcelona",
    location: "Barcelona, Spain",
    region: "Europe",
    country: "Spain",
    categories: ["Conference"],
    domains: ["Ethereum", "DeFi"],
    venueType: "in_person",
    startDateTime: new Date("2025-07-12T09:00:00+02:00"),
    endDateTime: new Date("2025-07-14T18:00:00+02:00"),
    links: ["https://ethbarcelona.com"],
    socials: ["https://twitter.com/ETHBarcelona"],
    communities: ["https://t.me/ethbarcelona"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 30, tempmin: 22, temp: 26, humidity: 65 },
  },
  {
    id: 4,
    name: "ETHSingapore",
    location: "Singapore",
    region: "Asia",
    country: "Singapore",
    categories: ["Conference"],
    domains: ["Ethereum", "Web3"],
    venueType: "in_person",
    startDateTime: new Date("2025-09-05T09:00:00+08:00"),
    endDateTime: new Date("2025-09-08T18:00:00+08:00"),
    links: ["https://ethsingapore.com"],
    socials: ["https://twitter.com/ETHSingapore"],
    communities: ["https://t.me/ethsingapore"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 33, tempmin: 27, temp: 30, humidity: 80 },
  },
  {
    id: 5,
    name: "Devcon",
    location: "Bangkok, Thailand",
    region: "Asia",
    country: "Thailand",
    categories: ["Conference"],
    domains: ["Ethereum", "Web3"],
    venueType: "in_person",
    startDateTime: new Date("2025-11-12T09:00:00+07:00"),
    endDateTime: new Date("2025-11-15T18:00:00+07:00"),
    links: ["https://devcon.org"],
    socials: ["https://twitter.com/EFDevcon"],
    communities: ["https://t.me/devcon"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 32, tempmin: 25, temp: 28, humidity: 75 },
  },
  {
    id: 6,
    name: "ETHLisbon",
    location: "Lisbon, Portugal",
    region: "Europe",
    country: "Portugal",
    categories: ["Hackathon"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-10-18T09:00:00+01:00"),
    endDateTime: new Date("2025-10-20T18:00:00+01:00"),
    links: ["https://ethlisbon.org"],
    socials: ["https://twitter.com/ETHLisbon"],
    communities: ["https://t.me/ethlisbon"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 24, tempmin: 16, temp: 20, humidity: 60 },
  },
  {
    id: 7,
    name: "ETHTokyo",
    location: "Tokyo, Japan",
    region: "Asia",
    country: "Japan",
    categories: ["Hackathon"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-04-12T09:00:00+09:00"),
    endDateTime: new Date("2025-04-14T18:00:00+09:00"),
    links: ["https://ethtokyo.com"],
    socials: ["https://twitter.com/ETHTokyo"],
    communities: ["https://t.me/ethtokyo"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 18, tempmin: 10, temp: 14, humidity: 70 },
  },
  {
    id: 8,
    name: "ETHBerlin",
    location: "Berlin, Germany",
    region: "Europe",
    country: "Germany",
    categories: ["Hackathon"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-08-23T09:00:00+02:00"),
    endDateTime: new Date("2025-08-25T18:00:00+02:00"),
    links: ["https://ethberlin.org"],
    socials: ["https://twitter.com/ETHBerlin"],
    communities: ["https://t.me/ethberlin"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 26, tempmin: 16, temp: 21, humidity: 60 },
  },
  {
    id: 9,
    name: "ETHNewYork",
    location: "New York, USA",
    region: "North America",
    country: "United States",
    categories: ["Hackathon"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-05-10T09:00:00-04:00"),
    endDateTime: new Date("2025-05-12T18:00:00-04:00"),
    links: ["https://ethnewyork.com"],
    socials: ["https://twitter.com/ETHNewYork"],
    communities: ["https://t.me/ethnewyork"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 22, tempmin: 12, temp: 17, humidity: 65 },
  },
  {
    id: 10,
    name: "ETHRio",
    location: "Rio de Janeiro, Brazil",
    region: "South America",
    country: "Brazil",
    categories: ["Conference"],
    domains: ["Ethereum"],
    venueType: "in_person",
    startDateTime: new Date("2025-03-14T09:00:00-03:00"),
    endDateTime: new Date("2025-03-17T18:00:00-03:00"),
    links: ["https://ethrio.org"],
    socials: ["https://twitter.com/ETHRio"],
    communities: ["https://t.me/ethrio"],
    hasTimezone: true,
    weatherMetrics: { tempmax: 32, tempmin: 22, temp: 27, humidity: 80 },
  },
]

export const regions = [
  DEFAULT_FILTERS.region,
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Africa",
  "Oceania",
]
